{
 "title": "ToggleMaster - Observability Overview",
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU por namespace",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{container!=\"\",pod!=\"\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory por namespace",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_working_set_bytes{container!=\"\",pod!=\"\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Logs de ToggleMaster",
   "type": "logs",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "{namespace=~\"auth|flag|targeting|evaluation|analytics\"}"
    }
   ]
  }
 ]
}