apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag
  namespace: flag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flag
  template:
    metadata:
      labels:
        app: flag
    spec:
      containers:
      - name: flag
        image: 063484726576.dkr.ecr.us-east-1.amazonaws.com/flags-service:c6665be9168fc7ec98d18d09cc27f10a3c22c47b
        ports:
        - containerPort: 8002
        envFrom:
        - secretRef:
            name: flag-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
