apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag
  namespace: flag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flag
  template:
    metadata:
      labels:
        app: flag
    spec:
      containers:
      - name: flag
        image: 248063312521.dkr.ecr.us-east-1.amazonaws.com/flags-service:f5c9285cacd0571a0e6ca84ae00db30fce985308
        ports:
        - containerPort: 8002
        envFrom:
        - secretRef:
            name: flag-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: OTEL_SERVICE_NAME
          value: flag-service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-gateway-opentelemetry-collector.observability.svc.cluster.local:4318
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.namespace=togglemaster, deployment.environment=dev, k8s.namespace.name=flag
