apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: flag
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6L3Bvc3RncmVzOnBvc3RncmVzMTIzQGZsYWdzLWRiLmNmOHN1N3F0amE2eS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9wb3N0Z3Jlcz9zc2xtb2RlPXJlcXVpcmU=
  AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZS5hdXRoLnN2Yy5jbHVzdGVyLmxvY2FsOjgw
