apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: 248063312521.dkr.ecr.us-east-1.amazonaws.com/auth-service:3475b1d4724c6bea1537092251222fa7f9d2ebb0
        ports:
        - containerPort: 8001
        envFrom:
        - secretRef:
            name: auth-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: OTEL_SERVICE_NAME
          value: auth-service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-gateway-opentelemetry-collector.observability.svc.cluster.local:4318
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.namespace=togglemaster, deployment.environment=dev, k8s.namespace.name=auth
        - name: OTEL_LOGS_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_TRACES_EXPORTER
          value: otlp  
