apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: 837177764356.dkr.ecr.us-east-1.amazonaws.com/auth-service:7a4f6d321b063acb9453a08d27690134a7d54ff0
        ports:
        - containerPort: 8001
        envFrom:
        - secretRef:
            name: auth-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
