apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 84.5.0
    helm:
      releaseName: kube-prometheus-stack
      values: |
        grafana:
          enabled: true
          defaultDashboardsEnabled: true
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: observability
              provider:
                allowUiUpdates: true
            
            datasources:
              enabled: true
              label: grafana_datasource
              defaultDatasourceEnabled: true
              isDefaultDatasource: true
              uid: prometheus

        additionalDashboards:
          - name: Loki
            uid: loki
            type: Loki
            access: proxy
            url: http://loki:3100
            isDefault: false
            editable: true
            jsonData:
              maxlines: 1000

        prometheus-node-exporter:
          enabled: false    

        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
            podMonitorSelector: {}
            podMonitorNamespaceSelector: {}
            
          alertmaneger:
            enabled: true

  destination:
      server: https://kubernetes.default.svc
      namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true