apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting
  namespace: targeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: targeting
  template:
    metadata:
      labels:
        app: targeting
    spec:
      containers:
      - name: targeting
        image: 063484726576.dkr.ecr.us-east-1.amazonaws.com/targeting-service:11869e06f44ab0c21b97c388949212245fff0d1d
        ports:
        - containerPort: 8003
        envFrom:
        - secretRef:
            name: targeting-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
