apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting
  namespace: targeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: targeting
  template:
    metadata:
      labels:
        app: targeting
    spec:
      containers:
      - name: targeting
        image: 248063312521.dkr.ecr.us-east-1.amazonaws.com/targeting-service:0565e2387e3d7b0e8a0aa571988f556d9ed0fd7c
        ports:
        - containerPort: 8003
        envFrom:
        - secretRef:
            name: targeting-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
