apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation
  namespace: evaluation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evaluation
  template:
    metadata:
      labels:
        app: evaluation
    spec:
      serviceAccountName: minha-app-sa
      containers:
        - name: evaluation
          image: 248063312521.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:f5c9285cacd0571a0e6ca84ae00db30fce985308
          ports:
            - containerPort: 8004
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          envFrom:
            - secretRef:
                name: evaluation-secrets
            - secretRef:
                name: aws-credentials
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_URL
            - name: OTEL_SERVICE_NAME
              value: evaluation-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-gateway-opentelemetry-collector.observability.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.namespace=togglemaster, deployment.environment=dev, k8s.namespace.name=evaluation