apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: 063484726576.dkr.ecr.us-east-1.amazonaws.com/analytics-service:c3123051c5f06b0fde4662278c223ad28174ae0b
          envFrom:
            - secretRef:
                name: aws-credentials
            - secretRef:
                name: analytics-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"