apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: 248063312521.dkr.ecr.us-east-1.amazonaws.com/analytics-service:11869e06f44ab0c21b97c388949212245fff0d1d
          envFrom:
            - secretRef:
                name: aws-credentials
            - secretRef:
                name: analytics-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"